fixtures:
  repositories:
    registry:
      repo: 'git://github.com/puppetlabs/puppetlabs-registry.git'
      ref: '1.1.3'
    chocolatey:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.1.0'
    chocolatey:
      repo: 'git://github.com/chocolatey/puppet-chocolatey.git'
      ref: '1.2.6'
  symlinks:
    reportslack: "#{source_dir}"
