fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.1.0'
    puppetserver_gem:
      repo: 'git://github.com/puppetlabs/puppetlabs-puppetserver_gem.git'
      ref: '0.1.0'
    inifile:
      repo: 'git://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: '1.4.2'
  symlinks:
    reportslack: "#{source_dir}"
