---
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation' && bundle exec rake metadata_lint"
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.8
    env: PUPPET_GEM_VERSION="~> 4.3"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.2"
notifications:
  email: nicolas@corrarello.com
